version: "3"
services:
  auth:
    build: 
      context: src/services/auth
    tty: true
    volumes:
      - ./src/services/auth:/go/src/auth
      - ./src/shared:/go/src/auth/shared
    ports:
      - 8000:8000
  gateway:
    build: 
      context: src/services/gateway
    tty: true
    volumes:
      - ./src/services/gateway:/go/src/gateway
      - ./src/shared:/go/src/gateway/shared
    ports:
      - 8002:8000
  pveapi:
    build: 
      context: src/services/pveapi
    tty: true
    volumes:
      - ./src/services/pveapi:/go/src/pveapi
      - ./src/shared:/go/src/pveapi/shared
      - ~/.ssh/id_ed25519:/ssh/id_ed25519
    ports:
      - 8001:8000
  contest:
    build: 
      context: src/services/contest
    tty: true
    volumes:
      - ./src/services/contest:/go/src/contest
      - ./src/shared:/go/src/contest/shared
    ports:
      - 8003:8000
  team:
    build: 
      context: src/services/team
    tty: true
    volumes:
      - ./src/services/team:/go/src/team
      - ./src/shared:/go/src/team/shared
    ports:
      - 8004:8000
  question:
    build: 
      context: src/services/question
    tty: true
    volumes:
      - ./src/services/question:/go/src/question
      - ./src/shared:/go/src/question/shared
    ports:
      - 8005:8000

  db:
    image: mysql:8.0
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/logs:/var/log/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/sample.sql:/docker-entrypoint-initdb.d/sample.sql

    environment:
      - MYSQL_DATABASE=ctf
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis/data:/data"
      - "./redis/redis.conf:/usr/local/etc/redis/redis.conf"
  nfs:
    build: 
      context: nfs
    privileged: true
    ports:
      - "2049:2049"    # NFS データポート
      - "20048:20048"  # NFS マウントポート    
    volumes:
      - nfs-data:/share
      - "./nfs/exports:/etc/exports"
    tty: true
  # traefik:
  #   image: "traefik:v3.1"
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./traefik

volumes:
  nfs-data:
    name: "nfs-data"