#cloud-config
hostname: 1-1-8
fqdn: 1-1-8
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: 9iYILfzVsE14FyeV
      shell: /bin/bash
      lock_passwd: false
      ssh_pwauth: "1"
packages:
    - git
    - curl
    - qemu-guest-agent
