#cloud-config
hostname: 1-1-5
fqdn: 1-1-5
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: n9t$7bA$!6vKFzwJ
      shell: /bin/bash
      lock_passwd: false
      ssh_pwauth: "1"
packages:
    - git
    - curl
    - qemu-guest-agent
