#cloud-config
hostname: 1-1-7
fqdn: 1-1-7
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: kcG*pCZ%QVSkHyg$
      shell: /bin/bash
      lock_passwd: false
      ssh_pwauth: "1"
packages:
    - git
    - curl
    - qemu-guest-agent
