#cloud-config
hostname: ctf-contestName-1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: user
      shell: /bin/bash
      ssh-authorized-keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+8AQAnsp3Klkz/4GXOdd+vVt4yPSUoTsjX5MCz3EbC nowhereman@windows-11.local
        - fiuhewaioufea
packages:
    - git
    - curl
