#cloud-config
hostname: question-test2-clone
fqdn: question-test2-clone
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/bash
      lock_passwd: false
      ssh-authorized-keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+8AQAnsp3Klkz/4GXOdd+vVt4yPSUoTsjX5MCz3EbC nowhereman@windows-11.local
        - ssh-ed25519 AAAAfewafeawfewafewfewafewfewfewafewfwaefwaefwafwefgwefpoewopjoiwjoi Test@feajii
packages:
    - git
    - curl
