#cloud-config
hostname: question-test2
fqdn: question-test2
ssh_pwauth: 1
users:
    - name: username
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: username
      shell: /bin/bash
      lock_passwd: false
      ssh-authorized-keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+8AQAnsp3Klkz/4GXOdd+vVt4yPSUoTsjX5MCz3EbC nowhereman@windows-11.local
        - ssh-ed25519 AAAAfewafeawfewafewfewafewfewfewafewfwaefwaefwafwefgwefpoewopjoiwjoi Test@feajii
      ssh_pwauth: "1"
packages:
    - git
    - curl
