#cloud-config
hostname: question_test
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      passwd: user
      shell: /bin/bash
      ssh-authorized-keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+8AQAnsp3Klkz/4GXOdd+vVt4yPSUoTsjX5MCz3EbC nowhereman@windows-11.local
        - test_ssh
packages:
    - git
    - curl
