#cloud-config
hostname: testcloudinit
fqdn: testcloudinit
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: user
      shell: /bin/bash
      lock_passwd: false
      ssh-authorized-keys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+8AQAnsp3Klkz/4GXOdd+vVt4yPSUoTsjX5MCz3EbC nowhereman@windows-11.local
        - feiajfioejaiwojo
      ssh_pwauth: "1"
packages:
    - git
    - curl
