#cloud-config
hostname: test2
fqdn: test2
ssh_pwauth: 1
users:
    - name: nowhereman
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: lennoN
      shell: /bin/bash
      lock_passwd: false
      ssh-authorized-keys:
        - ""
      ssh_pwauth: "1"
packages:
    - git
    - curl
    - qemu-guest-agent
