#cloud-config
hostname: test10
fqdn: test10
ssh_pwauth: 1
users:
    - name: user
      sudo: ALL=(ALL) NOPASSWD:ALL
      plain_text_passwd: user
      shell: /bin/bash
      lock_passwd: false
      ssh-authorized-keys:
        - ""
      ssh_pwauth: "1"
packages:
    - git
    - curl
    - qemu-guest-agent
